version: '2.4'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: task_management,task_management_test
    ports:
      - "5432:5432"
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
    networks:
      - dockernet
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "docker"
  #     PGADMIN_DEFAULT_PASSWORD: "docker"
  #   ports:
  #     - "16543:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - dockernet
  nestjs:
    build: .
    ports:
      - "${PORT}:${PORT}"
      - "9225:9225"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - dockernet
    command: yarn start:debug
networks:
  dockernet:
